services:
  mysql:
    image: mysql:8.0
    container_name: sleepsia-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sleepsia_reporting
      MYSQL_USER: sleepsia
      MYSQL_PASSWORD: sleepsia
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
